---
- hosts: web
  tasks:
    - name: install multiple app
      ansible.builtin.package:
        name: '{{item}}'
        state: present
        with_items:
         
          - git
          - tree
          - java
          - ansible  
